openapi: "3.0.0"
info:
  version: "1.0.0"
  title: Speaker Data API
servers:
  - url: "https://www.spinorama.org/api"
paths:
  /speakerData:
    get:
      summary: Get speaker data
      description: Returns a list of all speakers or information for a single speaker if speakerName is provided
      parameters:
        - in: query
          name: speakerName
          description: The name of the speaker to retrieve information for
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    bio:
                      type: string
                    talks:
                      type: array
                      items:
                        type: object
                        properties:
                          title:
                            type: string
                          description:
                            type: string
        '404':
          description: Not Found
